// <auto-generated />
namespace School2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedenrolledenrolledcandclassc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedenrolledenrolledcandclassc));
        
        string IMigrationMetadata.Id
        {
            get { return "201806191845214_added enrolled, enrolled(c), and class(c)"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
